In [2]:
import numpy as py

In [3]:
from numpy import array

In [4]:
from scipy.linalg import svd

In [24]:
from numpy import dot

In [31]:
A =py.array([[1,2,3],[4,5,6],[7,8,9]])


In [32]:
U,s,VT=svd(A)
print(U)
print(s)
print(VT)

[[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]
[1.68481034e+01 1.06836951e+00 3.33475287e-16]
[[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]


In [33]:
sigma=py.zeros((A.shape[0],A.shape[1]))
sigma

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
sigma =sigma[:A.shape[1],:A.shape[1]]=py.diag(s)
sigma

array([[1.68481034e+01, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.06836951e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 3.33475287e-16]])

In [36]:
B=U.dot(sigma.dot(VT))
B

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

<h3>Find Peudoinverse through SVD.</h3>

In [41]:
C=py.array([[1,2],[3,4],[5,6],[7,8]])


In [51]:
U,s,VT=svd(C)
s

array([14.2690955 ,  0.62682823])

In [42]:
d =1/s

In [47]:
D=py.zeros(C.shape)


In [50]:
D[:C.shape[1],:C.shape[1]]=py.diag(d)
D

array([[0.07008153, 0.        ],
       [0.        , 1.59533338],
       [0.        , 0.        ],
       [0.        , 0.        ]])